return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  main = 'nvim-treesitter.configs',
  opts = {
    ensure_installed = {
      'bash',
      'diff',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      'html',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'powershell',
      'python',
      'query',
      'rust',
      'toml',
      'vim',
      'vimdoc',
      'yaml',
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'ruby' },
    },
    indent = { enable = true, disable = { 'ruby' } },
  },
}
